const delivery = 'Complimentary express delivery across India and returns within 14 days. Ships in a Saint Orson garment case.';
const mainImage = (name) => `products/main/${name}.jpg`;
const detailImage = (name) => `products/details/${name}.jpg`;

const base = {
  colors: ['Black', 'Navy', 'Wine'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  care: 'Specialist dry clean only. Store with room to breathe and steam gently from the reverse.',
  delivery,
  signature: 'Designed in Mumbai · Finished by hand',
  images: ['dress-campaign.webp', 'dress-detail.webp', 'dress-rear.webp'],
};

export const PRODUCTS = [
  {
    ...base,
    slug: 'merino-roll-neck',
    number: '01',
    name: 'Merino roll neck',
    display: ['Merino', 'roll neck'],
    category: 'Knitwear',
    chapter: 'Morning structure',
    price: 32500,
    colors: ['Black', 'Charcoal', 'Ivory'],
    description: 'A fine-gauge merino layer with a clean neck and a close, unforced line through the body.',
    material: 'Extra-fine merino wool spun for warmth without weight, with fully fashioned shoulders.',
    construction: 'Tubular neck, linked seams and ribbed cuffs shaped to recover after every wear.',
    fitNote: 'Model is 178 cm and wears size S. Cut close without clinging.',
    storyTitle: ['Warmth,', 'without', 'weight.'],
    storyCopy: 'The yarn is compact enough to sit under tailoring and soft enough to wear directly against the skin.',
    movementTitle: ['Built for', 'the first', 'layer.'],
    movementCopy: 'A narrow silhouette keeps the shoulder clean beneath a coat while the ribbed neck holds its shape.',
    materialLabel: 'Extra-fine merino · 18 gauge',
    images: [mainImage('merino-roll-neck-main-v1'), detailImage('merino-roll-neck-detail-v1'), base.images[2]],
    shopImage: mainImage('merino-roll-neck-main-v1'),
    shopPosition: '58% center',
  },
  {
    ...base,
    slug: 'gabardine-trouser',
    number: '02',
    name: 'Gabardine trouser',
    display: ['Gabardine', 'trouser'],
    category: 'Tailoring',
    chapter: 'Morning structure',
    price: 48500,
    colors: ['Stone', 'Navy', 'Black'],
    sizes: ['28', '30', '32', '34', '36'],
    description: 'A high-rise trouser cut from compact wool gabardine, with a long leg and one precise break.',
    material: 'Pure wool gabardine with a dry hand, natural recovery and a tightly defined twill.',
    construction: 'Extended waistband, internal brace buttons, slanted pockets and a hand-finished hem.',
    fitNote: 'Model wears size 30. High rise with a relaxed thigh and straight leg.',
    storyTitle: ['A line', 'drawn', 'cleanly.'],
    storyCopy: 'The cloth holds the crease without stiffness, allowing the leg to remain composed through a full day.',
    movementTitle: ['Made to', 'move through', 'the city.'],
    movementCopy: 'Room through the thigh gives ease in motion; the structured hem keeps the silhouette exact.',
    materialLabel: 'Wool gabardine · 280 gsm',
    images: [mainImage('gabardine-trouser-main-v1'), detailImage('gabardine-trouser-detail-v1'), base.images[2]],
    shopImage: mainImage('gabardine-trouser-main-v1'),
    shopPosition: '58% center',
  },
  {
    ...base,
    slug: 'silk-evening-shirt',
    number: '03',
    name: 'Silk evening shirt',
    display: ['Silk evening', 'shirt'],
    category: 'Shirting',
    chapter: 'Evening chapter',
    price: 36500,
    colors: ['Ivory', 'Black', 'Wine'],
    description: 'A fluid silk shirt with a softened collar, concealed placket and cuffs made to turn back once.',
    material: 'Heavy silk crepe chosen for its matte face, fluid fall and subtle movement under evening light.',
    construction: 'French seams, concealed shell buttons and a hand-set collar with minimal internal structure.',
    fitNote: 'Model is 178 cm and wears size S. Relaxed through the body.',
    storyTitle: ['Light,', 'held in', 'silk.'],
    storyCopy: 'The matte surface catches only the edge of the light, leaving the shape to speak first.',
    movementTitle: ['An evening', 'shirt that', 'breathes.'],
    movementCopy: 'Volume through the back allows the silk to move freely without losing the clean front line.',
    materialLabel: 'Silk crepe · 30 momme',
    images: [mainImage('silk-evening-shirt-main-v1'), detailImage('silk-evening-shirt-detail-v1'), base.images[2]],
    shopImage: mainImage('silk-evening-shirt-main-v1'),
    shopPosition: '45% center',
  },
  {
    ...base,
    slug: 'milano-coat',
    number: '04',
    name: 'Milano coat',
    display: ['Milano', 'coat'],
    category: 'Outerwear',
    chapter: 'En route',
    price: 108000,
    colors: ['Navy', 'Black', 'Charcoal'],
    description: 'A long double-faced wool coat with a decisive shoulder, quiet lapel and almost no visible structure.',
    material: 'Double-faced wool and cashmere, hand-split at every edge for warmth without a heavy lining.',
    construction: 'Hand-finished seams, horn buttons, internal passport pocket and a full floating canvas.',
    fitNote: 'Model is 188 cm and wears size M. Designed for a tailored layer beneath.',
    storyTitle: ['Structure,', 'without', 'the weight.'],
    storyCopy: 'Each seam is split and closed by hand, allowing two layers of cloth to behave as one.',
    movementTitle: ['The coat', 'between', 'places.'],
    movementCopy: 'Its long back vent opens in stride and settles cleanly the moment movement stops.',
    materialLabel: 'Wool cashmere · Double face',
    images: [mainImage('milano-coat-main-v1'), detailImage('milano-coat-detail-v1'), base.images[2]],
    shopImage: mainImage('milano-coat-main-v1'),
    shopPosition: '70% center',
  },
  {
    ...base,
    slug: 'cashmere-polo-knit',
    number: '05',
    name: 'Cashmere polo knit',
    display: ['Cashmere', 'polo knit'],
    category: 'Knitwear',
    chapter: 'A day, well cut',
    price: 34500,
    colors: ['Black', 'Navy', 'Ivory'],
    description: 'A fine cashmere polo with an open collar, clean placket and the restraint of a tailored shirt.',
    material: 'Two-ply cashmere knitted densely enough to hold a collar while remaining exceptionally soft.',
    construction: 'Fully fashioned armholes, linked side seams and a reinforced open placket.',
    fitNote: 'Model is 188 cm and wears size M. Close through chest and waist.',
    storyTitle: ['Softness,', 'given', 'discipline.'],
    storyCopy: 'A compact knit gives the collar its line while the cashmere keeps the garment easy against the body.',
    movementTitle: ['Made for', 'the hours', 'between.'],
    movementCopy: 'The open neck moves from morning tailoring to evening without asking for a change.',
    materialLabel: 'Two-ply cashmere · 16 gauge',
    images: [mainImage('cashmere-polo-knit-main-v1'), detailImage('cashmere-polo-knit-detail-v1'), base.images[2]],
    shopImage: mainImage('cashmere-polo-knit-main-v1'),
    shopPosition: '61% center',
  },
  {
    ...base,
    slug: 'pleated-wool-trouser',
    number: '06',
    name: 'Pleated wool trouser',
    display: ['Pleated wool', 'trouser'],
    category: 'Tailoring',
    chapter: 'A day, well cut',
    price: 56500,
    colors: ['Ivory', 'Navy', 'Black'],
    sizes: ['28', '30', '32', '34', '36'],
    description: 'A full-cut wool trouser with inward pleats, a high waist and a long, uninterrupted fall.',
    material: 'Tropical wool woven for warm climates, balancing a crisp surface with exceptional breathability.',
    construction: 'Double inward pleats, extended tab closure, side adjusters and a generous hand-finished hem.',
    fitNote: 'Model wears size 30. High rise, full thigh and tapered lower leg.',
    storyTitle: ['Volume,', 'placed with', 'purpose.'],
    storyCopy: 'The pleats open only in movement, preserving a clean front line when the wearer is still.',
    movementTitle: ['A fuller', 'way to', 'move.'],
    movementCopy: 'Extra cloth through the hip creates ease without sacrificing the exactness of the taper.',
    materialLabel: 'Tropical wool · 240 gsm',
    images: [mainImage('pleated-wool-trouser-main-v1'), detailImage('pleated-wool-trouser-detail-v1'), base.images[2]],
    shopImage: mainImage('pleated-wool-trouser-main-v1'),
    shopPosition: '48% center',
  },
  {
    ...base,
    slug: 'draped-silk-dress',
    number: '07',
    name: 'Draped silk dress',
    display: ['Draped', 'silk dress'],
    category: 'Evening / Dresses',
    chapter: 'Evening chapter',
    price: 58500,
    description: 'A study in movement. Cut from weighty silk satin, gathered once at the waist and left to fall with its own quiet logic.',
    material: '100% silk satin. Cut on the bias for fluid movement, with a double-layered crossover bodice.',
    construction: 'Hand-finished asymmetric gathering, internal waist stay, French seams and a clean invisible side closure.',
    fitNote: 'Model is 178 cm and wears size S. Cut close through the bodice with a fluid skirt.',
    storyTitle: ['One fold', 'leads to', 'the next.'],
    storyCopy: 'The neckline crosses without fastening. The waist gathers into a single sculpted line, allowing the silk to move rather than hold its shape.',
    movementTitle: ['Designed for', 'the room,', 'not the mirror.'],
    movementCopy: 'The weighted hem settles after every step. The back remains clean; all the drama belongs to the front.',
    materialLabel: 'Silk satin · 32 momme',
    signature: 'Cut in Como · Finished in Paris',
    images: [mainImage('draped-silk-dress-main-v1'), detailImage('draped-silk-dress-detail-v1'), base.images[2]],
    shopImage: mainImage('draped-silk-dress-main-v1'),
    shopPosition: 'center 20%',
  },
  {
    ...base,
    slug: 'relaxed-tailored-blazer',
    number: '08',
    name: 'Relaxed tailored blazer',
    display: ['Relaxed', 'tailored blazer'],
    category: 'Tailoring',
    chapter: 'Morning structure',
    price: 89500,
    colors: ['Ivory', 'Navy', 'Black'],
    description: 'An ivory single-breasted blazer with softened construction and enough length to balance a high-waisted trouser.',
    material: 'Lightweight wool and silk with a dry, refined surface suited to the Indian climate.',
    construction: 'Half canvas, hand-padded lapels, natural shoulder and a breathable butterfly lining.',
    fitNote: 'Model is 178 cm and wears size S. Relaxed through the body.',
    storyTitle: ['Tailoring,', 'allowed to', 'breathe.'],
    storyCopy: 'Structure is kept only where it earns its place: the lapel, the shoulder line and the fall of the front.',
    movementTitle: ['A jacket', 'for warmer', 'light.'],
    movementCopy: 'The open lining and light canvas preserve shape without trapping weight against the body.',
    materialLabel: 'Wool silk · Half canvas',
    images: [mainImage('relaxed-tailored-blazer-main-v1'), detailImage('relaxed-tailored-blazer-detail-v1'), base.images[2]],
    shopImage: mainImage('relaxed-tailored-blazer-main-v1'),
    shopPosition: '48% center',
  },
  {
    ...base,
    slug: 'silk-print-scarf',
    number: '09',
    name: 'Silk print scarf',
    display: ['Silk print', 'scarf'],
    category: 'Accessories',
    chapter: 'Morning structure',
    price: 16500,
    colors: ['Navy', 'Wine', 'Ivory'],
    sizes: ['One size'],
    description: 'A hand-rolled silk scarf in navy and restrained oxblood, drawn to sit neatly at the neck or pocket.',
    material: 'Pure silk twill with a precise diagonal weave and a hand-screened geometric border.',
    construction: 'Hand-rolled edges completed in Mumbai, with each corner finished individually.',
    fitNote: 'Measures 68 × 68 cm. Designed for neck, pocket or bag.',
    storyTitle: ['A small', 'gesture,', 'finished well.'],
    storyCopy: 'The scale of the print is considered at the fold, so the border remains visible however it is worn.',
    movementTitle: ['Color,', 'kept in', 'reserve.'],
    movementCopy: 'Navy carries the composition; oxblood appears only at the edge and in motion.',
    materialLabel: 'Silk twill · Hand rolled',
    images: [mainImage('silk-print-scarf-main-v1'), detailImage('silk-print-scarf-detail-v1'), base.images[2]],
    shopImage: mainImage('silk-print-scarf-main-v1'),
    shopPosition: 'center',
  },
  {
    ...base,
    slug: 'weekend-holdall',
    number: '10',
    name: 'Weekend holdall',
    display: ['Weekend', 'holdall'],
    category: 'Leather goods',
    chapter: 'En route',
    price: 66500,
    colors: ['Chestnut', 'Black', 'Oxblood'],
    sizes: ['One size'],
    description: 'A structured leather holdall proportioned for two nights, with quiet hardware and an uninterrupted top line.',
    material: 'Full-grain vegetable-tanned leather selected for a deep patina and a firm but supple hand.',
    construction: 'Reinforced base, hand-painted edges, solid brass zip and a cotton drill interior with three pockets.',
    care: 'Wipe with a soft dry cloth. Condition sparingly and store filled inside its dust bag.',
    fitNote: 'Cabin compatible. 48 × 30 × 22 cm with a removable shoulder strap.',
    storyTitle: ['Made for', 'leaving', 'well.'],
    storyCopy: 'The body is cut from broad panels so the leather, rather than decorative seams, defines the object.',
    movementTitle: ['Two nights,', 'carried', 'quietly.'],
    movementCopy: 'The short handles sit close to the hand while the structured base keeps the bag composed in transit.',
    materialLabel: 'Full-grain leather · Brass',
    images: [mainImage('weekend-holdall-main-v1'), detailImage('weekend-holdall-detail-v1'), base.images[2]],
    shopImage: mainImage('weekend-holdall-main-v1'),
    shopPosition: 'center',
  },
];

export const PRODUCT_BY_SLUG = Object.fromEntries(PRODUCTS.map((product) => [product.slug, product]));
export const productHref = (slug) => `#/product/${slug}`;
export const formatINR = (value) => `₹${value.toLocaleString('en-IN')}`;
